services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - cab432
    volumes:
      - mongodata:/data/db

  app:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/11404680_ass1
    container_name: assignment1
    networks:
      - cab432
    volumes:
      - ./API/public/gifs:/app/public/gifs
    environment:
      PORT: 3000
      SECRET_KEY: ge1d646asfer57sf54
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "80:3000"
    depends_on:
      - mongo

networks:
  cab432: 
    driver: bridge

volumes:
  mongodata:
