services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - cab432
    volumes:
      - mongodata:/data/db

  app:
    image: test
    container_name: test
    networks:
      - cab432
    environment:
      PORT: 3000
      SECRET_KEY: ge1d646asfer57sf54
      MONGODB_URI: mongodb://mongo:27017
    ports:
      - "80:3000"
    depends_on:
      - mongo

networks:
  cab432: 
    driver: bridge

volumes:
  mongodata:
